/* eslint-disable strict */
// app/service/news.js
const Service = require('egg').Service;

class NewsService extends Service {
  async list(pageIndex = '', pageSize = '20') {
    try {
      // read config
      const { serverUrl } = this.config.readhub;
      // 热门话题
      const topic = `${serverUrl}topic?lastCursor=${pageIndex}&pageSize=${pageSize}`;
      // use build-in http client to GET hacker-news api
      const result = await this.ctx.curl(topic,
        {
          followRedirect: true, // followRedirect {Boolean} - 将HTTP 3xx响应作为重定向。默认为false。
          dataType: 'json',
        }
      );
      if (result.status === 200) {
        const tempData = {
          data: [
            {
              id: '7M8gRtPpAsq',
              newsArray: [
                {
                  id: 1598138,
                  url: 'https://www.jiemian.com/article/3070688.html',
                  title: '测试标题1',
                  siteName: '界面',
                  mobileUrl: 'https://www.jiemian.com/article/3070688.html',
                  autherName: '刘雨静 ·',
                  duplicateId: 1,
                  publishDate: '2019-04-24T04:51:00.000Z',
                  language: 'zh-cn',
                  statementType: 1,
                },
              ],
              createdAt: '2019-04-24T05:31:52.621Z',
              eventData: [
                {
                  id: 17532,
                  topicId: '7M8gRtPpAsq',
                  eventType: 10,
                  entityId: '7wEetdSy7L0',
                  entityType: 'company',
                  entityName: '可口可乐',
                  state: 1,
                  createdAt: '2019-04-24T05:31:52.762Z',
                  updatedAt: '2019-04-24T05:31:52.762Z',
                },
              ],
              publishDate: '2019-04-23T21:33:15.761Z',
              summary: '测试内容123 测试内容123测试内容123测试内容123测试内容123测试内容123测试内容123测试内容123测试内容123测试内容123测试内容123测试内容123测试内容123测试内容123测试内容123',
              title: '测试标题1',
              updatedAt: '2019-04-24T06:00:12.248Z',
              timeline: '7IB9Oe6VXmn',
              order: 134679,
              hasInstantView: false,
              extra: {
                instantView: false,
              },
            },
            {
              id: '7M8hYuRzrJU',
              newsArray: [
                {
                  id: 1598129,
                  url: 'https://www.jiemian.com/article/3070842.html',
                  title: '测试标题2',
                  siteName: '界面',
                  mobileUrl: 'https://www.jiemian.com/article/3070842.html',
                  autherName: '柯晓斌 ·',
                  duplicateId: 1,
                  publishDate: '2019-04-24T05:16:00.000Z',
                  language: 'zh-cn',
                  statementType: 1,
                },
                {
                  id: 1598192,
                  url: 'https://tech.sina.cn/i/gn/2019-04-24/detail-ihvhiewr7967432.d.html?from=wap',
                  title: '滴滴对安全产品与技术部门架构进行升级调整',
                  siteName: '新浪科技',
                  mobileUrl: 'https://tech.sina.cn/i/gn/2019-04-24/detail-ihvhiewr7967432.d.html?from=wap',
                  autherName: '界面',
                  duplicateId: 1,
                  publishDate: '2019-04-24T05:39:36.000Z',
                  language: 'zh-cn',
                  statementType: 1,
                },
                {
                  id: 1598131,
                  url: 'http://tech.qq.com/a/20190424/005160.htm',
                  title: '深网 | 滴滴升级集团安全产品技术部架构',
                  siteName: '腾讯科技',
                  mobileUrl: 'http://tech.qq.com/a/20190424/005160.htm',
                  autherName: 'www.qq.com',
                  duplicateId: 2,
                  publishDate: '2019-04-24T05:19:10.000Z',
                  language: 'zh-cn',
                  statementType: 1,
                },
                {
                  id: 1598193,
                  url: 'http://www.donews.com/news/detail/1/3043476.html',
                  title: '滴滴升级安全产品技术部架构',
                  siteName: 'DoNews',
                  mobileUrl: 'http://www.donews.com/news/detail/1/3043476.html',
                  autherName: '',
                  duplicateId: 2,
                  publishDate: '2019-04-24T05:57:12.000Z',
                  language: 'zh-cn',
                  statementType: 1,
                },
              ],
              createdAt: '2019-04-24T05:21:44.213Z',
              eventData: [],
              publishDate: '2019-04-23T21:59:30.579Z',
              summary: '测试内容2测试内容2测试内容2测试内容2测试内容2测试内容2测试内容2测试内容2测试内容2测试内容2测试内容2测试内容2测试内容2',
              title: '测试标题2',
              updatedAt: '2019-04-24T06:01:55.868Z',
              timeline: '7L2ZP5neYdb',
              order: 134678,
              hasInstantView: true,
              extra: {
                instantView: true,
              },
            },
            {
              id: '7M8fXXcBhjj',
              newsArray: [
                {
                  id: 1598125,
                  url: 'https://wallstreetcn.com/articles/3516906',
                  title: '张勇卸任天猫法定代表人,蒋凡接任。',
                  siteName: '华尔街见闻',
                  mobileUrl: 'https://wallstreetcn.com/articles/3516906',
                  autherName: '',
                  duplicateId: 1,
                  publishDate: '2019-04-23T20:37:01.000Z',
                  language: 'zh-cn',
                  statementType: 1,
                },
                {
                  id: 1598121,
                  url: 'https://www.chinaventure.com.cn/cmsmodel/news/detail/343673.shtml',
                  title: '张勇卸任天猫法定代表人，天猫总裁蒋凡接任',
                  siteName: '投中网',
                  mobileUrl: 'https://www.chinaventure.com.cn/cmsmodel/news/detail/343673.shtml',
                  autherName: 'miya',
                  duplicateId: 4,
                  publishDate: '2019-04-24T04:50:00.000Z',
                  language: 'zh-cn',
                  statementType: 1,
                },
                {
                  id: 1598122,
                  url: 'https://www.jiemian.com/article/3070774.html',
                  title: '快看 | 张勇卸任天猫法定代表人及董事长兼总经理职务，蒋凡接任',
                  siteName: '界面',
                  mobileUrl: 'https://www.jiemian.com/article/3070774.html',
                  autherName: '于浩 ·',
                  duplicateId: 5,
                  publishDate: '2019-04-24T05:11:00.000Z',
                  language: 'zh-cn',
                  statementType: 1,
                },
              ],
              createdAt: '2019-04-24T05:13:17.388Z',
              eventData: [
                {
                  id: 17533,
                  topicId: '7M8fXXcBhjj',
                  eventType: 4,
                  entityId: '7M8kIQnzu8s',
                  entityType: 'company',
                  entityName: '天猫',
                  state: 1,
                  createdAt: '2019-04-24T05:57:27.600Z',
                  updatedAt: '2019-04-24T05:57:27.600Z',
                },
              ],
              publishDate: '2019-04-23T21:14:36.334Z',
              summary: '测试内容3测试内容3测试内容3测试内容3测试内容3测试内容3测试内容3测试内容3测试内容3测试内容3测试内容3测试内容3测试内容3测试内容3',
              title: '测试标题3',
              updatedAt: '2019-04-24T05:56:42.237Z',
              timeline: '7LrA8UPhmnj',
              order: 134677,
              hasInstantView: false,
              extra: {
                instantView: false,
              },
            },
            {
              id: '7M86fqJ2QBK',
              newsArray: [
                {
                  id: 1597965,
                  url: 'http://tech.qq.com/a/20190424/001698.htm',
                  title: '特斯拉宣布将重新推出Model S/X中较低售价的标准航距款',
                  siteName: '腾讯科技',
                  mobileUrl: 'http://tech.qq.com/a/20190424/001698.htm',
                  autherName: 'www.qq.com',
                  duplicateId: 1,
                  publishDate: '2019-04-24T00:50:39.000Z',
                  language: 'zh-cn',
                  statementType: 1,
                },
                {
                  id: 1597966,
                  url: 'http://tech.qq.com/a/20190424/003621.htm',
                  title: '特斯拉对Model X和S重大升级 动力续航再上台阶',
                  siteName: '腾讯科技',
                  mobileUrl: 'http://tech.qq.com/a/20190424/003621.htm',
                  autherName: 'www.qq.com',
                  duplicateId: 2,
                  publishDate: '2019-04-24T02:46:32.000Z',
                  language: 'zh-cn',
                  statementType: 1,
                },
                {
                  id: 1597975,
                  url: 'https://tech.sina.cn/it/2019-04-24/detail-ihvhiewr7937540.d.html?from=wap',
                  title: '特斯拉推新版Model S和X，马斯克将公布汽车火灾统计',
                  siteName: '新浪科技',
                  mobileUrl: 'https://tech.sina.cn/it/2019-04-24/detail-ihvhiewr7937540.d.html?from=wap',
                  autherName: '新京报',
                  duplicateId: 4,
                  publishDate: '2019-04-24T03:16:14.000Z',
                  language: 'zh-cn',
                  statementType: 1,
                },
              ],
              createdAt: '2019-04-24T03:22:09.188Z',
              eventData: [],
              publishDate: '2019-04-23T19:23:28.772Z',
              summary: '测试内容4测试内容4测试内容4测试内容4测试内容4测试内容4',
              title: '测试标题4',
              updatedAt: '2019-04-24T05:48:11.102Z',
              timeline: '7M8as7BgAPs',
              order: 134669,
              hasInstantView: true,
              extra: {
                instantView: true,
              },
            },
            {
              id: '7M876MJrVbm',
              newsArray: [
                {
                  id: 1597958,
                  url: 'https://tech.sina.cn/it/2019-04-24/detail-ihvhiqax4747062.d.html?from=wap',
                  title: '被指自燃的特斯拉已送往体验中心检查 现场戒备严密',
                  siteName: '新浪科技',
                  mobileUrl: 'https://tech.sina.cn/it/2019-04-24/detail-ihvhiqax4747062.d.html?from=wap',
                  autherName: '澎湃新闻',
                  duplicateId: 1,
                  publishDate: '2019-04-24T02:43:28.000Z',
                  language: 'zh-cn',
                  statementType: 1,
                },
                {
                  id: 1597959,
                  url: 'http://tech.ifeng.com/a/20190424/45502285_0.shtml',
                  title: '被指自燃的特斯拉已送往体验中心检查 现场戒备严密',
                  siteName: '凤凰科技',
                  mobileUrl: 'http://tech.ifeng.com/a/20190424/45502285_0.shtml',
                  autherName: '',
                  duplicateId: 1,
                  publishDate: '2019-04-24T02:45:57.000Z',
                  language: 'zh-cn',
                  statementType: 1,
                },
                {
                  id: 1597962,
                  url: 'https://tech.163.com/19/0424/11/EDH9ULQV00097U7T.html',
                  title: '特斯拉疑似自燃进展：被送到特斯拉体验中心待检',
                  siteName: '网易科技',
                  mobileUrl: 'https://tech.163.com/19/0424/11/EDH9ULQV00097U7T.html',
                  autherName: '',
                  duplicateId: 2,
                  publishDate: '2019-04-24T03:17:28.000Z',
                  language: 'zh-cn',
                  statementType: 1,
                },
                {
                  id: 1598116,
                  url: 'http://tech.qq.com/a/20190424/005012.htm',
                  title: '被指自燃的特斯拉检测有了进展：专家初步判定为电池短路',
                  siteName: '腾讯科技',
                  mobileUrl: 'http://tech.qq.com/a/20190424/005012.htm',
                  autherName: 'www.qq.com',
                  duplicateId: 4,
                  publishDate: '2019-04-24T05:00:23.000Z',
                  language: 'zh-cn',
                  statementType: 1,
                },
                {
                  id: 1598123,
                  url: 'https://tech.163.com/19/0424/13/EDHGE9RA00097U7R.html',
                  title: '被指自燃的特斯拉检测新进展：初步判定为电池短路',
                  siteName: '网易科技',
                  mobileUrl: 'https://tech.163.com/19/0424/13/EDHGE9RA00097U7R.html',
                  autherName: '',
                  duplicateId: 5,
                  publishDate: '2019-04-24T05:10:52.000Z',
                  language: 'zh-cn',
                  statementType: 1,
                },
              ],
              createdAt: '2019-04-24T03:18:57.542Z',
              eventData: [],
              publishDate: '2019-04-23T19:20:16.259Z',
              summary: '测试我测试我测试我测试我测试我测试我测试我测试我测试我测试我测试我测试我测试我测试我测试我测试我测试我测试我测试我测试我',
              title: '测试哈哈哈测试',
              updatedAt: '2019-04-24T05:15:06.423Z',
              timeline: '7M8aoyvrRlP',
              order: 134668,
              hasInstantView: true,
              extra: {
                instantView: true,
              },
            },
            {
              id: '7M87736dTc1',
              newsArray: [
                {
                  id: 1597888,
                  url: 'https://tech.163.com/19/0424/10/EDH7S5TJ00097U7S.html',
                  title: 'Realme创始人李炳忠正式宣布品牌进入国内市场',
                  siteName: '网易科技',
                  mobileUrl: 'https://tech.163.com/19/0424/10/EDH7S5TJ00097U7S.html',
                  autherName: '',
                  duplicateId: 2,
                  publishDate: '2019-04-24T02:41:09.000Z',
                  language: 'zh-cn',
                  statementType: 1,
                },
                {
                  id: 1597889,
                  url: 'https://www.jiemian.com/article/3070250.html',
                  title: '快看 | OPPO系智能手机品牌Realme宣布正式进入国内市场',
                  siteName: '界面',
                  mobileUrl: 'https://www.jiemian.com/article/3070250.html',
                  autherName: '于浩 ·',
                  duplicateId: 4,
                  publishDate: '2019-04-24T02:43:00.000Z',
                  language: 'zh-cn',
                  statementType: 1,
                },
                {
                  id: 1597892,
                  url: 'https://tech.sina.cn/t/2019-04-24/detail-ihvhiqax4747921.d.html?from=wap',
                  title: '直击|Realme创始人李炳忠正式宣布品牌进入国内市场',
                  siteName: '新浪科技',
                  mobileUrl: 'https://tech.sina.cn/t/2019-04-24/detail-ihvhiqax4747921.d.html?from=wap',
                  autherName: '新浪科技',
                  duplicateId: 6,
                  publishDate: '2019-04-24T02:48:28.000Z',
                  language: 'zh-cn',
                  statementType: 1,
                },
                {
                  id: 1597982,
                  url: 'https://www.tmtpost.com/3903493.html',
                  title: '海外起家的OPPO独立品牌Realme宣布回归国内，也主打性价比丨钛快讯',
                  siteName: '钛媒体',
                  mobileUrl: 'https://www.tmtpost.com/3903493.html',
                  autherName: '钛媒体瞬眼播报',
                  duplicateId: 11,
                  publishDate: '2019-04-24T03:16:00.000Z',
                  language: 'zh-cn',
                  statementType: 1,
                },
              ],
              createdAt: '2019-04-24T02:53:21.848Z',
              eventData: [],
              publishDate: '2019-04-23T18:54:42.683Z',
              summary: '演示内容测试演示内容测试演示内容测试演示内容测试演示内容测试演示内容测试演示内容测试演示内容测试',
              title: 'OPPO 测试6测试6测试6测试6测试6测试6测试6测试6测试6测试6测试6测试6',
              updatedAt: '2019-04-24T05:57:56.642Z',
              timeline: '7JIoQPe10K6',
              order: 134663,
              hasInstantView: true,
              extra: {
                instantView: true,
              },
            },
            {
              id: '7M86BcxDV9V',
              newsArray: [
                {
                  id: 1597852,
                  url: 'http://tech.qq.com/a/20190423/008446.htm',
                  title: 'TCL集团2019年Q1净利润7.79亿元，同比增长6.6%',
                  siteName: '腾讯科技',
                  mobileUrl: 'http://tech.qq.com/a/20190423/008446.htm',
                  autherName: '',
                  duplicateId: 1,
                  publishDate: '2019-04-23T13:03:48.000Z',
                  language: 'zh-cn',
                  statementType: 1,
                },
                {
                  id: 1597853,
                  url: 'https://tech.sina.cn/it/2019-04-24/detail-ihvhiewr7878192.d.html?from=wap',
                  title: 'TCL集团首季净利增6.6% 面板业回暖言之尚早',
                  siteName: '新浪科技',
                  mobileUrl: 'https://tech.sina.cn/it/2019-04-24/detail-ihvhiewr7878192.d.html?from=wap',
                  autherName: '第一财经',
                  duplicateId: 2,
                  publishDate: '2019-04-23T16:43:12.000Z',
                  language: 'zh-cn',
                  statementType: 1,
                },
                {
                  id: 1598185,
                  url: 'https://www.tmtpost.com/nictation/3903242.html',
                  title: 'TCL集团首季净利增6.6%,面板业回暖言之尚早',
                  siteName: '钛媒体',
                  mobileUrl: 'https://www.tmtpost.com/nictation/3903242.html',
                  autherName: '',
                  duplicateId: 4,
                  publishDate: '2019-04-24T00:56:00.000Z',
                  language: 'zh-cn',
                  statementType: 1,
                },
                {
                  id: 1597854,
                  url: 'https://tech.sina.cn/it/2019-04-24/detail-ihvhiqax4744950.d.html?from=wap',
                  title: 'TCL集团第一季度营收296亿元 同比增长15.5%',
                  siteName: '新浪科技',
                  mobileUrl: 'https://tech.sina.cn/it/2019-04-24/detail-ihvhiqax4744950.d.html?from=wap',
                  autherName: '新浪科技',
                  duplicateId: 5,
                  publishDate: '2019-04-24T02:34:02.000Z',
                  language: 'zh-cn',
                  statementType: 1,
                },
                {
                  id: 1598025,
                  url: 'https://www.jiemian.com/article/3070567.html',
                  title: '快看 | TCL集团发布重组后首份财报，一季度净利同比增 27.7%',
                  siteName: '界面',
                  mobileUrl: 'https://www.jiemian.com/article/3070567.html',
                  autherName: '于浩 ·',
                  duplicateId: 6,
                  publishDate: '2019-04-24T03:47:00.000Z',
                  language: 'zh-cn',
                  statementType: 1,
                },
              ],
              createdAt: '2019-04-24T02:46:14.998Z',
              eventData: [],
              publishDate: '2019-04-23T18:52:29.911Z',
              summary: '测试内容长度测试内容长度测试内容长度测试内容长度测试内容长度测试内容长度测试内容长度测试内容长度',
              title: '测试内容长度限制',
              updatedAt: '2019-04-24T05:56:37.258Z',
              timeline: '7JhuPHhNP22',
              order: 134658,
              hasInstantView: true,
              extra: {
                instantView: true,
              },
            },
            {
              id: '7M86mkbwK8j',
              newsArray: [
                {
                  id: 1597820,
                  url: 'http://tech.qq.com/a/20190423/007589.htm',
                  title: '一线丨华为成立投资公司哈勃科技 白熠任董事长',
                  siteName: '腾讯科技',
                  mobileUrl: 'http://tech.qq.com/a/20190423/007589.htm',
                  autherName: 'www.qq.com',
                  duplicateId: 1,
                  publishDate: '2019-04-23T11:10:07.000Z',
                  language: 'zh-cn',
                  statementType: 1,
                },
                {
                  id: 1597821,
                  url: 'http://tech.ifeng.com/a/20190423/45502165_0.shtml',
                  title: '华为成立投资公司哈勃科技：注册资本7亿元，白熠任董事长',
                  siteName: '凤凰科技',
                  mobileUrl: 'http://tech.ifeng.com/a/20190423/45502165_0.shtml',
                  autherName: '',
                  duplicateId: 2,
                  publishDate: '2019-04-23T11:30:00.000Z',
                  language: 'zh-cn',
                  statementType: 1,
                },
                {
                  id: 1597822,
                  url: 'http://www.donews.com/news/detail/1/3043427.html',
                  title: '华为成立创投公司哈勃科技 白熠任董事长',
                  siteName: 'DoNews',
                  mobileUrl: 'http://www.donews.com/news/detail/1/3043427.html',
                  autherName: '赵晋杰',
                  duplicateId: 3,
                  publishDate: '2019-04-23T23:27:39.000Z',
                  language: 'zh-cn',
                  statementType: 1,
                },
              ],
              createdAt: '2019-04-24T02:44:22.732Z',
              eventData: [],
              publishDate: '2019-04-23T18:51:06.354Z',
              summary: '不想加班想加班想加班想加班想加班想加班想加班想加班想加班想加班想加班想加班想加班',
              title: '不想加班',
              updatedAt: '2019-04-24T03:16:38.592Z',
              timeline: '7M8FHTugPmj',
              order: 134657,
              hasInstantView: true,
              extra: {
                instantView: true,
              },
            },
            {
              id: '7M86CEFyNC8',
              newsArray: [
                {
                  id: 1597784,
                  url: 'https://pe.pedaily.cn/201904/442485.shtml',
                  title: '快讯|小象互娱完成1.25亿A+轮融资，PDD领投腾讯跟投',
                  siteName: '投资界',
                  mobileUrl: 'https://pe.pedaily.cn/201904/442485.shtml',
                  autherName: 'S',
                  duplicateId: 1,
                  publishDate: '2019-04-24T01:19:00.000Z',
                  language: 'zh-cn',
                  statementType: 1,
                },
              ],
              createdAt: '2019-04-24T02:40:08.752Z',
              eventData: [],
              publishDate: '2019-04-23T18:42:42.291Z',
              summary: '厉害了测试sdsad厉害了测试sdsad厉害了测试sdsad厉害了测试sdsad厉害了测试sdsad厉害了测试sdsad厉害了测试sdsad厉害了测试sdsad',
              title: '厉害了测试',
              updatedAt: '2019-04-24T02:42:42.293Z',
              timeline: '7M8F6FHblTj',
              order: 134656,
              hasInstantView: false,
              extra: {
                instantView: false,
              },
            },
            {
              id: '7M86jM1fZnx',
              newsArray: [
                {
                  id: 1597872,
                  url: 'https://www.iyiou.com/p/98273.html',
                  title: 'IPO路上的瑞幸：亏损16亿，仍铁了心要和星巴克决战？',
                  siteName: '亿欧',
                  mobileUrl: 'https://www.iyiou.com/p/98273.html',
                  autherName: '刘旷',
                  duplicateId: 13,
                  publishDate: '2019-04-24T02:45:00.000Z',
                  language: 'zh-cn',
                  statementType: 2,
                },
                {
                  id: 1597780,
                  url: 'https://tech.163.com/19/0424/10/EDH6LUGR00097U7R.html',
                  title: '连咖啡完成2.06亿元融资，已重新回归盈利状态',
                  siteName: '网易科技',
                  mobileUrl: 'https://tech.163.com/19/0424/10/EDH6LUGR00097U7R.html',
                  autherName: '',
                  duplicateId: 1,
                  publishDate: '2019-04-24T02:20:17.000Z',
                  language: 'zh-cn',
                  statementType: 1,
                },
                {
                  id: 1597778,
                  url: 'https://36kr.com/p/5197847',
                  title: '连咖啡完成2.06亿元融资，已重新回归盈利状态',
                  siteName: '36Kr',
                  mobileUrl: 'https://36kr.com/p/5197847',
                  autherName: '',
                  duplicateId: 1,
                  publishDate: '2019-04-23T16:00:00.000Z',
                  language: 'zh-cn',
                  statementType: 1,
                },
                {
                  id: 1597782,
                  url: 'https://tech.sina.cn/i/gn/2019-04-24/detail-ihvhiewr7932712.d.html?from=wap',
                  title: '连咖啡完成2.06亿元融资 已重新回归盈利状态',
                  siteName: '新浪科技',
                  mobileUrl: 'https://tech.sina.cn/i/gn/2019-04-24/detail-ihvhiewr7932712.d.html?from=wap',
                  autherName: '新浪科技综合',
                  duplicateId: 1,
                  publishDate: '2019-04-24T02:25:50.000Z',
                  language: 'zh-cn',
                  statementType: 1,
                },
                {
                  id: 1597781,
                  url: 'https://www.iyiou.com/p/98272.html',
                  title: '连咖啡宣布完成2.06亿元B3轮融资，并已重回盈利状态',
                  siteName: '亿欧',
                  mobileUrl: 'https://www.iyiou.com/p/98272.html',
                  autherName: '胡博娅',
                  duplicateId: 2,
                  publishDate: '2019-04-24T02:22:00.000Z',
                  language: 'zh-cn',
                  statementType: 1,
                },
                {
                  id: 1597779,
                  url: 'http://tech.qq.com/a/20190424/003255.htm',
                  title: '深网|连咖啡宣布完成2.06亿元B3轮融资 重回盈利状态',
                  siteName: '腾讯科技',
                  mobileUrl: 'http://tech.qq.com/a/20190424/003255.htm',
                  autherName: '',
                  duplicateId: 2,
                  publishDate: '2019-04-24T02:16:52.000Z',
                  language: 'zh-cn',
                  statementType: 1,
                },
                {
                  id: 1597759,
                  url: 'https://www.pingwest.com/a/186828',
                  title: '图解：瑞幸咖啡上市招股书关键数据',
                  siteName: 'PingWest 品玩',
                  mobileUrl: 'https://www.pingwest.com/a/186828',
                  autherName: '李晓贤',
                  duplicateId: 6,
                  publishDate: '2019-04-24T01:19:53.000Z',
                  language: 'zh-cn',
                  statementType: 1,
                },
                {
                  id: 1597760,
                  url: 'https://wallstreetcn.com/articles/3516791?from=widgets',
                  title: 'O2O最后一曲赞歌',
                  siteName: '华尔街见闻',
                  mobileUrl: 'https://wallstreetcn.com/articles/3516791?from=widgets',
                  autherName: '',
                  duplicateId: 7,
                  publishDate: '2019-04-24T01:32:00.000Z',
                  language: 'zh-cn',
                  statementType: 1,
                },
                {
                  id: 1597879,
                  url: 'https://www.chinaventure.com.cn/cmsmodel/news/detail/343668.shtml',
                  title: '全面回归盈利，连咖啡再获2.06亿元融资',
                  siteName: '投中网',
                  mobileUrl: 'https://www.chinaventure.com.cn/cmsmodel/news/detail/343668.shtml',
                  autherName: 'miya',
                  duplicateId: 10,
                  publishDate: '2019-04-24T02:26:00.000Z',
                  language: 'zh-cn',
                  statementType: 1,
                },
              ],
              createdAt: '2019-04-24T02:35:53.053Z',
              eventData: [
                {
                  id: 17531,
                  topicId: '7M86jM1fZnx',
                  eventType: 1,
                  entityId: '7KBOinfMgI0',
                  entityType: 'company',
                  entityName: '连咖啡',
                  state: 1,
                  createdAt: '2019-04-24T02:39:25.958Z',
                  updatedAt: '2019-04-24T02:39:25.958Z',
                },
              ],
              publishDate: '2019-04-23T18:40:34.299Z',
              summary: '我要喝咖啡我要喝咖啡我要喝咖啡我要喝咖啡我要喝咖啡我要喝咖啡我要喝咖啡我要喝咖啡我要喝咖啡我要喝咖啡我要喝咖啡我要喝咖啡',
              title: '我要喝咖啡',
              updatedAt: '2019-04-24T02:40:34.301Z',
              timeline: '7M8EXdKhHwb',
              order: 134655,
              hasInstantView: true,
              extra: {
                instantView: true,
              },
            },
          ],
          pageSize: 10,
          totalItems: 34649,
          totalPages: 3465,
        };
        return tempData || result.data;
      }
      return [];
    } catch (error) {
      this.logger.error(error);
      return [];
    }
  }
  async saveDB(list) {
    try {
      const newsClient = this.app.database;
      list.data.forEach(item => {
        // 插入
        newsClient.insert('news', {
          id: item.id,
          order: item.order,
          title: item.title,
          jsonstr: JSON.stringify(item),
          createdAt: new Date(item.createdAt).getTime(),
          updatedAt: new Date(item.updatedAt).getTime(),
        }).then(result => {
          // 判断更新成功
          const updateSuccess = result.affectedRows === 1;
          // 入库成功说明 错误容错量初始化
          this.app.cache.errorNum = 0;
          this.logger.info(item.id + ' > ' + updateSuccess);
        }).catch(error => {
          // 链接数据库失败
          if (error.code == 'ECONNREFUSED') {
            this.app.cache.mysqlState = false;
          }
          // 入库失败错误机制触发
          this.app.cache.errorNum += 1;
          this.logger.error(error);
        });
      });
    } catch (error) {
      // 数据库异常失败错误机制触发
      this.app.cache.errorNum += 1;
      this.logger.error(error);
    }
  }
}

module.exports = NewsService;
